apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: web
      image: mauroslucios/nodekubernetes:v1
      ports:
        - containerPort: 3003

---

apiVersion: v1
kind: Pod
metadata:
  name: meupod
  labels:
    app: web
spec:
  containers:
    - name: web
      image: mauroslucios/nodekubernetes:v1
      ports:
        - containerPort: 3003